name: Testing

## Actions that will be executed when you push code currently none
on:
  pull_request:
    branches:
      - main
      - develop

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew test
  ## 4
  android_instrumented_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
  generate_reports:
    runs-on: [ macos-latest ]
    needs: [unit_tests, android_instrumented_tests]
    steps:
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Instrumentation report
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew jacocoTestReport
      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: dashboard/build/reports/coverage/androidTest/debug
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: dashboard/build/reports/coverage/androidTest/debug
      - name: Upload Test Report
        run: bash <(curl -s https://codecov.io/bash) -f "dashboard/build/reports/coverage/androidTest/debug/report.xml"
